  openapi: 3.0.0
  info:
    title: Auth-Service API
    version: 1.0.0
    description: API for user authentication, OTP, Google login, and profile management.

  servers:
    - url: http://localhost:3004/api
      description: Local development server

  components:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT

    schemas:
      SignupRequest:
        type: object
        required:
          - first_name
          - last_name
          - email
          - password
          - repeat_password
        properties:
          first_name:
            type: string
            example: John
          last_name:
            type: string
            example: Doe
          email:
            type: string
            format: email
            example: john.doe@example.com
          password:
            type: string
            format: password
            example: mysecret123
          repeat_password:
            type: string
            format: password
            example: mysecret123

      LoginRequest:
        type: object
        required:
          - email
          - password
        properties:
          email:
            type: string
            format: email
            example: john.doe@example.com
          password:
            type: string
            format: password
            example: mysecret123

      GoogleLoginRequest:
        type: object
        required:
          - idToken
        properties:
          idToken:
            type: string
            example: ya29.a0AfH6SMB...

      VerifyOtpRequest:
        type: object
        required:
          - email
          - otp
        properties:
          email:
            type: string
            format: email
          otp:
            type: string
            example: "123456"

      ResendOtpRequest:
        type: object
        required:
          - email
        properties:
          email:
            type: string
            format: email

      ResetPasswordRequest:
        type: object
        required:
          - email
          - otp
          - password
          - repeat_password
        properties:
          email:
            type: string
          otp:
            type: string
          password:
            type: string
          repeat_password:
            type: string

  paths:
    /signup:
      post:
        summary: Register a new user
        requestBody:
          required: true
          content:
            multipart/form-data:
              schema:
                allOf:
                  - $ref: '#/components/schemas/SignupRequest'
                  - type: object
                    properties:
                      profile_image:
                        type: string
                        format: binary
        responses:
          '201':
            description: User created successfully
          '409':
            description: User already exists
          '400':
            description: Validation error

    /verify-otp:
      post:
        summary: Verify OTP sent to email
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyOtpRequest'
        responses:
          '200':
            description: OTP verified successfully
          '400':
            description: Invalid OTP or expired

    /password-reset/otp/resend:
      post:
        summary: Resend OTP to email (also for forgot password)
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResendOtpRequest'
        responses:
          '200':
            description: OTP sent successfully
          '404':
            description: Email not found

    /login:
      post:
        summary: Login with email and password
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginRequest'
        responses:
          '200':
            description: Login successful
          '401':
            description: Invalid credentials

    /password-reset:
      post:
        summary: Reset password using OTP
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResetPasswordRequest'
        responses:
          '200':
            description: Password reset successful
          '400':
            description: OTP expired or invalid

    /logout:
      get:
        summary: Logout the user
        responses:
          '200':
            description: Logout successful

    /user/{id}:
      get:
        summary: Get user details
        security:
          - bearerAuth: []
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        responses:
          '200':
            description: User details fetched
          '404':
            description: User not found

    /user/update/{id}:
      patch:
        summary: Update user profile
        security:
          - bearerAuth: []
        parameters:
          - name: id
            in: path
            required: true
            schema:
              type: string
        requestBody:
          content:
            multipart/form-data:
              schema:
                type: object
                properties:
                  first_name:
                    type: string
                  last_name:
                    type: string
                  profile_image:
                    type: string
                    format: binary
        responses:
          '200':
            description: User updated
          '400':
            description: Validation error

    /google-login:
      post:
        summary: Google login
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GoogleLoginRequest'
        responses:
          '200':
            description: Google login successful
          '409':
            description: Email already exists for manual login
