version: '3.8'
services:
  api-gateway:
    build: ../api-gateway
    ports:
      - "4000:4000"
    depends_on:
      - auth-service
    networks:
      - backend

  auth-service:
    build: ./auth-service
    ports:
      - "3004:3004"
    env_file:
      - ./auth-service/.env
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crystal-event
    ports:
    - "5432:5432"


networks:
  backend:
