version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: crystal-event

  app: 
    image: auth-service-event:latest
    ports: 
      - 13000:3004
   
